server:
  port: 8081
  servlet:
    context-path: /sso-auth-server

security:
  oauth2:
    client:
      client-secret: intellias-secret
      client-id: intellias-client
    authorization:
      check-token-access: permitAll()
      token-key-access: permitAll()