version: "3.1"
services:
  ms-authorization-server:
    container_name: ms-authorization-server
    build:
      context: ../..
      dockerfile: configs/ms-authorization-server/Dockerfile
    ports:
      - '8083:8081'
    networks:
      oauth2-network:
        aliases:
          - ms-authorization-server

networks:
  oauth2-network:
    external: true
