version: "3.1"
services:
  ms-resource-server:
    container_name: ms-resource-server
    build:
      context: ../..
      dockerfile: configs/ms-resource-server/Dockerfile
    ports:
      - '8082:8082'
    networks:
      oauth2-network:
        aliases:
          - ms-resource-server

networks:
  oauth2-network:
    external: true
